name             'pyenv'
maintainer       'Shane da Silva'
maintainer_email 'shane@causes.com'
license          'Apache 2.0'
description      'Manages pyenv and its installed Python versions, also providing several LWRPs.'
long_description 'Please refer to README.md'
version          '0.0.1'

supports 'ubuntu'
supports 'debian'
supports 'freebsd'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'amazon'
supports 'scientific'
supports 'suse'
supports 'mac_os_x'
